#
# Format:
# 
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: squarestays-backend
  stack: bamboo-mri-1.9.2
  config:
    BUNDLE_WITHOUT: "development:test"
    S3_ACCESS_KEY_ID: 
    S3_SECRET_ACCESS_KEY: 
    S3_BUCKET: squarestays-img-production
    FB_APP_ID: 
    FB_APP_SECRET: 
    FRONTEND_PATH: http://squarestays.com
    SECRET_TOKEN: 4fafcf33a55a5b7d6cd2be869e9f450b65ea004e421c05b459ebb2643e7a6b3201d5f1e2da0ce7310102c7d48368b0d100087f73545fd14aff0de8050f818a61
    COOKIE_STORE_KEY: _SquareStaysProductionBackEnd_session
    # MAILER_SENDER: "SquareStays.com <noreply@squarestays.com>"
    PEPPER_TOKEN: Z8TxukxAnyxxjRgs6jSB3Y3v4AzHjFvPFxpaENsJCnrkDUuYgTcaWywccE3CA8Gdgs6jSB3Y3v4AzHjFvPFxpaENsJCnrkDUWywccE3CA8Gdgs6jSB3YAnyxxjRgs6jS

staging:
  app: backend-heypal
  stack: bamboo-mri-1.9.2
  config:
    BUNDLE_WITHOUT: "development:test"
    S3_ACCESS_KEY_ID: 
    S3_SECRET_ACCESS_KEY: 
    S3_BUCKET: squarestays-img-staging
    FB_APP_ID: 
    FB_APP_SECRET: 
    FRONTEND_PATH: http://frontend-heypal.heroku.com
    SECRET_TOKEN: 4fafcf33a55a5b7d6cd2be869e9f450b65ea004e421c05b459ebb2643e7a6b3201d5f1e2da0ce7310102c7d48368b0d100087f73545fd14aff0de8050f818a61
    COOKIE_STORE_KEY: _SquareStaysStagingBackEnd_session
    # MAILER_SENDER: 'SquareStays.com <noreply@squarestays.com>' ERROR
    PEPPER_TOKEN: Z8TxukxAnyxxjRgs6jSB3Y3v4AzHjFvPFxpaENsJCnrkDUuYgTcaWywccE3CA8Gdgs6jSB3Y3v4AzHjFvPFxpaENsJCnrkDUWywccE3CA8Gdgs6jSB3YAnyxxjRgs6jS
    DATABASE_URL: mysql2://heypaladmin:HYpl99db@heypal-useast-1.c7xsjolvk9oh.us-east-1.rds.amazonaws.com/heypaldb