defaults: &defaults
  S3_ACCESS_KEY_ID: AKIAJOJEIAZ6LOVHDFDA
  S3_SECRET_ACCESS_KEY: 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
  FB_APP_ID: 221413484589066
  FB_APP_SECRET: 719daf903365b4bab445a2ef5c54c2ea
  TW_APP_ID: HYFCbVk0FUoxg3f3bi3lA
  TW_APP_SECRET: YpzH8iTJU5BXmid3cm3i1I9xC57qmQM5Z0kWqpkHA
  FRONTEND_PATH: 'http://localhost:3005'
  SECRET_TOKEN: 4fafcf33a55a5b7d6cd2be869e9f450b65ea004e421c05b459ebb2643e7a6b3201d5f1e2da0ce7310102c7d48368b0d100087f73545fd14aff0de8050f818a61
  MAILER_SENDER: SquareStays.com <noreply@squarestays.com>
  PEPPER_TOKEN: Z8TxukxAnyxxjRgs6jSB3Y3v4AzHjFvPFxpaENsJCnrkDUuYgTcaWywccE3CA8Gdgs6jSB3Y3v4AzHjFvPFxpaENsJCnrkDUWywccE3CA8Gdgs6jSB3YAnyxxjRgs6jS
  SITE_NAME: SquareStays.com
  SUPPORT_EMAIL: support@squarestays.com
  

  
development:
  <<: *defaults
  S3_BUCKET: squarestays-img-dev
  COOKIE_STORE_KEY: _SquareStaysDevelopmentBackEnd_session
  REDISTOGO_URL: redis://127.0.0.1:6379
  RAKISMET_KEY: 3eaaa95fa309
  RAKISMET_URL: http://squarestays.dev/
  

test:
  <<: *defaults
  STORAGE: filesystem
  CARRIER_STORAGE: file
  S3_BUCKET: squarestays-img-test
  COOKIE_STORE_KEY: _SquareStaysTestBackEnd_session
  REDISTOGO_URL: redis://127.0.0.1:6379