development:
  bucket: heypal-dev1
  access_key_id: AKIAJOJEIAZ6LOVHDFDA
  secret_access_key: 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
test:
  bucket: heypal-test1
  access_key_id: AKIAJOJEIAZ6LOVHDFDA
  secret_access_key: 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
production:
  bucket: heypal-prod1
  access_key_id: AKIAJOJEIAZ6LOVHDFDA
  secret_access_key: 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